services:
  debian:
    build:
      context: .
    # command: ["ls", "-la"]
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./src
          initial_sync: true
          target: /app/src
          ignore:
            - must_be_ignore
        # - action: sync+restart
        - action: rebuild
          path: ./etc
          target: /app/etc